name: cletus-container
on: [push]
jobs:
 docker-example:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build container image
        run: >
          docker build 
          --iidfile container.id .
      - name: Show image information
        run: docker image inspect $(cat container.id)